###

@path=http://localhost:8080/api

GET {{path}}/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6InNhbXVlbC5taWNoYXV4QGdtYWlsIiwic3ViIjoiNyIsImlhdCI6MTc0OTU1MTA2NywiZXhwIjoxNzQ5NjM3NDY3fQ.oqxPsWTZyI2npCL4AJnMMQy6Pdi2y3DE0aRlcTty_zNZKaCD_uP3Hod0Lq4pGENrA3Aa5BLGBQfL9LCANKDWlA

###

GET {{path}}/users/1

###

POST {{path}}/auth/register
Accept: application/json
Content-Type: application/json

{
 "email": "samuel.michaux@gmail",
 "password": "Sam12345$",
 "firstName": "sam",
 "lastName": "mich"
}

###
POST {{path}}/auth/login
Accept: application/json
Content-Type: application/json

{
 "email": "samuel.michaux@gmail",
 "password": "Sam12345$"
}

