###

@path=http://localhost:8080/api

GET {{path}}/users

###

GET {{path}}/users/1

###

POST {{path}}/auth/register
Accept: application/json
Content-Type: application/json

{
 "email": "samuel.michaux@gmail",
 "password": "Sam12345$",
 "firstName": "sam",
 "lastName": "mich"
}

###
POST {{path}}/auth/login
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6InNhbXVlbC5taWNoYXV4QGdtYWlsIiwic3ViIjoiNyIsImlhdCI6MTc0OTIxOTUwMCwiZXhwIjoxNzQ5MzA1OTAwfQ.am0US16TCZJTaYtn_YMNZYmImuvHsft5LrhMtAJiVSqyGa3Buf6H_wspGQiqxtaqi8z8VDLlhL5GdW3TV-VieA

{
 "email": "samuel.michaux@gmail",
 "password": "Sam12345$"
}

